### ISSUE TITLE
Great share ! But some help ?

### ISSUE THREAD

**Issue by Chestroled** [dmonty2/ArduinoMotionStairLights#2]
Hello there ! 

I first want to thank you for sharing your project on GitHub. I would like to do exactly the same thing and in some search i'm arrived here !

I will personnaly use : 
- 4m WS2812b led strip
- 1 Arduino nano
- 2 PIR hc-sr501 

Unfortunately I'm not very comfortable with C++ arduino coding since i'm still nooby ...
So I wonder if you can help me in this way and understand your code ?

the behavior I research is:
-  Figure how to configure the nimber of leds by step
- "idle" mode, no movement is detected, the 4 first and 4 last leds "breathe" in a selected color 
  (like this project : [http://www.instructables.com/id/How-to-bling-up-a-boring-staircase/](url) )

I assume than this function is provided by this code :

 `  if (timeOut+57000 < millis()) {        // idle state - 'breathe' the top and bottom LED to show program is looping

```
 breathe = breathe + change;
 strip.setPixelColor(0,0,0,breathe);
 strip.setPixelColor(116,0,0,breathe);
 strip.show();
 if (breathe == 100 || breathe == 0) change = -change;      // breathe the LED from 0 = off to 100 = fairly bright
 if (breathe == 100 || breathe == 0) delay (300);           // Pause at beginning and end of each breath
 delay(25); 
```

  }`
- Up and down sequence like yours ( fade in to orange and gradually warm white. after a delay without movement, fade out in the reverse way)

I will try by myself to understand your code, but your help will be very helpfull !

Thanks and sorry for my poor english ...

**Comment by dbalta06** [comment]
Help !!!

**Comment by dmonty2** [comment]
There is an "unstable" branch that now supports choosing the number of leds per stair.

Generally:
- An effect is randomly chosen.
- Direction of the animation is an array  ZERO -to- NUM_LEDS or NUM-LEDS -to- ZERO
- Each effect has "stages" which grow animate and shrink.
`enum Stage { off, stage_init, stage_grow, stage_init_run, stage_run, stage_init_dim, stage_dim };`
