### ISSUE TITLE
change Leds per stair ??

### ISSUE THREAD

**Issue by dbalta06** [dmonty2/ArduinoMotionStairLights#3]
Hi,

how can I change the Leds per stair ???

**Comment by dmonty2** [comment]
That is on the TODO list... very bottom of the page:
https://github.com/dmonty2/ArduinoMotionStairLights

**Comment by sajovicd** [comment]
Hello,
Any news on this?

That would be perfect.

**Comment by dmonty2** [comment]
I'll see what I can do.  No E.T.A.

**Comment by sajovicd** [comment]
That would be great, thank you.

**Comment by nicowater** [comment]
for me the same will 8 leds per step forwards and backwards
look in your sketch try to change it bud always a problem

**Comment by dmonty2** [comment]
I worked on it a bit... problem I'm having is that the RGB lights were mounted on the stairs and the arduino is in the wall under the stairs.  It is proving awkward programming and debugging it.  When I did the initial code is was done at a desk.  I'm considering running a second laptop at the arduino to remote desktop onto it to make the changes.

**Comment by dmonty2** [comment]
I've created an unstable development branch with some initial code to support adjusting LEDS_PER_STAIR.

The code compiles but has not been tested and may crash.

https://github.com/dmonty2/ArduinoMotionStairLights/blob/unstable/ArduinoMotionStairLights.ino

**Comment by nicowater** [comment]
Hello Dmonty2 happy that you wil working on the code
if you need help for testing i wil do it 
thanks

**Comment by sajovicd** [comment]
Hello, 
Today I tried your new code.
Now it is possible to set number of LED per stair - GREAT !!!
But after led goes off, there is always the last set of LED that is always on. If I started from top then the bottom 10 led (as per my setup), always stay on. If I started from bottom, then the upper 10 led's stays on.
Another problem is that I could only set up 120 led's if I try with 130+ it makes welcome rainbow but after rainbow is turned off nothing happens after... I was waiting for 10 minutes and also try PIR sensor if they are working, and voltmeter showed me 3.35V when PIR was triggered, so everything should work. Then I set up 120led's and everything is working except last set of led's wont turn off.
Hope you can figure it out why cant setup more than 120 leds.

**Comment by sajovicd** [comment]
I just found that when yellow-green blinking effect is, then all leds are shut down properly.

**Comment by nicowater** [comment]
i try now your code 
working great however the las step backward stay on 
so when the pir is activate up or down going okay but when he go back the last step stay on
probebly  by you is it the same

**Comment by dmonty2** [comment]
I'm just setting up a small breadboard now to test/debug...

**Comment by dmonty2** [comment]
Does yours crash on PIN_PIR_UP?

**Comment by dmonty2** [comment]
My arduino had some buggy pins.  The unstable branch is now debugged - try it now.

**Comment by dmonty2** [comment]
The number of leds issue is probably because I put the number of stairs/leds into too small of a data type.  I'll look at increasing the size.

**Comment by nicowater** [comment]
no it was not crash whit pin_pir_up
ow it working just fine great job 
now only lookking for the effect using one instead random how to choose  
looks like stand on ewalk and sparkle but gif random
really happy whit it

**Comment by dmonty2** [comment]
New upload - increased datatype size to support more LEDS.  I don't have enough leds to test it though.

**Comment by dmonty2** [comment]
For single effect in chooseEffects function - around line 123 uncomment:
//effect = effectFlicker; return;  // temporarily force effect for debugging: effectWalk, effectFlicker, effectFade6

Make sure you download the latest code as I just renamed those variables.

**Comment by nicowater** [comment]
tested whit 60 leds new is come 
Tested new code and working fine 
4/6/8/10/12/led per step working is okay
used the new code send me 5 minutes ago 
i save first your code than renamed those variables so i am sure i have the original code

**Comment by dmonty2** [comment]
@sajovicd please let me know if larger datatypes support the number of LEDs you are driving?

**Comment by nicowater** [comment]
tested 20 leds per step and working 
now i have maximum of 60 leds 
i have to wait til more led arrive

**Comment by sajovicd** [comment]
Hello,
Thanks for the GREAT work. 
It works now up to 250 LED's, if I try with more strange things are happening, 
For me that is enough.
One more wish, I already try but no luck... How to make more sparkling effect... 
I love sparkling :)

**Comment by nicowater** [comment]
Is it possible to place a LDR  in the system 
So the stair by daylight you don't need the light when it's dark it may start working

**Comment by dmonty2** [comment]
@sajovicd as one increases the number of LEDS you will experience strange problems due to voltage drop and memory on your controller.
https://github.com/FastLED/FastLED/issues/288

Sparkling is chosen on line 231.
```cpp
// Random choose an effect between enum: sparkle, pulsate1, pulsate2, flash
walk_effect = (WalkEffects)random8( 0, 4 ); 
// you could force it to always sparkle
walk_effect = sparkle;
```
Another option would be to have a weighted random number where the code prefers sparkle but will still show other effects randomly.   Add a function:
```cpp
void chooseWalkEffect(){
  randomSeed(millis());
  r = random8(1, 100);
  //walk_effect enum: sparkle, pulsate1, pulsate2, flash
  if ( r >= 0 && r <= 90 ){  // 90% it will sparkle and 10% for the rest...
    walk_effect = sparkle;
  } else if ( r > 90 && r <= 93 ){
    walk_effect = pulsate1;
  } else if ( r > 93 && r <= 96 ){
    walk_effect = pulsate2;
  } else {
    walk_effect = flash;
  } 
}

// then change line 231
//walk_effect = (WalkEffects)random8( 0, 4 ); 
chooseWalkEffect();
```

**Comment by dmonty2** [comment]
@nicowater  please test this out.  It is based on:
https://learn.adafruit.com/photocells/using-a-photocell
```cpp
// At the top where variables are declaired
#define PIN_PHOTO_CELL 0           // the cell and 10K pulldown are connected to a0
#define PHOTO_CELL_BRIGHTNESS 200  // adjust this value e.g. 10 Dark, 200 Dim, 500 Light, 800 Bright
int photoCellReading = 0;          // the analog reading from the analog resistor divider
long photoCellInterval = 60000;    // How often to read photocell 1000mills * 60sec
long previousPhotoCell = 0;        // millis counter for last photocell reading.
 

// Replace the loop function:
void loop() {
  currentMillis = millis();
  // analogRead will slow things down so only check sensor when lights are off on an interval timer.
  if (stage == off && currentMillis - previousPhotoCell > photoCellInterval){
    previousPhotoCell = currentMillis;
    photoCellReading = analogRead(PIN_PHOTO_CELL); 
  }  
  if (photoCellReading < PHOTO_CELL_BRIGHTNESS) {
    readSensors();
    if(currentMillis - previousMillis > effectInterval) {
      previousMillis = currentMillis;
      update_effect(); 
      FastLED.show();
    }
    if((currentMillis - previousOffMillis > offInterval) && stage == stage_run){
      stage = stage_init_dim;
      i = 0; r = 0; g = 0; b = 0;
    }
  }
}
```

**Comment by dmonty2** [comment]
This ticket issue is for adding support to change # leds per stair which has been done.  If you have a new issue or wish list item please create a new issue.

**Comment by nicowater** [comment]
Thanks Dean 

For the great support 

I try your code for the fotocel and hope it works

**Comment by dmonty2** [comment]
Closing this ticket.   Support for photo cell has moved to new issue.
https://github.com/dmonty2/ArduinoMotionStairLights/issues/6
