### ISSUE TITLE
Change Color to white

### ISSUE THREAD

**Issue by FraZoR15** [dmonty2/ArduinoMotionStairLights#4]
Hy, 

thanks for sharing the project, the code is amazing. 

For my stairs, i would prefer only white colored leds. 

Unfortunately i am a noob with palettes.. 

Can you please help me to change the color in white? 

Thank you!

**Comment by dmonty2** [comment]
// Quick and dirty - to make all the pallets white change the setPalette function to all white pallets:

```cpp
void setPalette(){
  // 16 pallets of white - there be dragons.
  for (uint8_t i = 0; i<16; i++){
    gPalette[i] = CRGB( 100, 100, 100 ); // White Red=100, Green=100, Blue=100
  }
}
```


// Then Change chooseEffects() function to use just one effect:
```cpp
void chooseEffects(){
  effect = ewalk;  // My favorite transition with random effect variations
}
```

**Comment by dmonty2** [comment]
There is a list of various whites here
https://github.com/FastLED/FastLED/blob/master/color.h

e.g.
```cpp
void setPalette(){
  // 16 pallets of white - there be dragons.
   for (uint8_t i = 0; i<16; i++){
     gPalette[i] = CRGB::Tungsten100W;
     //gPalette[i] = CRGB( 100, 100, 100 ); // White Red=100, Green=100, Blue=100
  }
}
```
