### ISSUE TITLE
Support for day/night photo cell

### ISSUE THREAD

**Issue by dmonty2** [dmonty2/ArduinoMotionStairLights#6]
@nicowater - moved photocell request to new issue.

I've updated the code in the unstable branch to include photocell support.

You will have to find and enable this near line 24
```cpp
#define PIN_PHOTO_CELL 0           // the cell and 10K pulldown are connected to a0
#define HAS_PHOTO_CELL false       // set to true if you have a photocell so lights only run at night.
#define PHOTO_CELL_BRIGHTNESS 200  // adjust this value e.g. 10 Dark, 200 Dim, 500 Light, 800 Bright
```
Please test and let me know if it works.  Thanks.

**Comment by nicowater** [comment]
Hello Dean 
i try this when i have the fotocel 
i have ordered the new cel only forget it is chinees new year 
during a few weeks longer but when i have it i test and let you know 
today i go to work maybe the has a fotocel for me dan i tested it and let you know as soon as posible

**Comment by ciprian288** [comment]
Hi,
the code is amazing and the sketch works very well, but how can I make it work only between sunset and dawn ...unfortunately i am a noob with sunset library ?
Thank you!

**Comment by dmonty2** [comment]
My guess will be to treat it just like standard outdoor night motion lights.  Make sure the photocell is in a location that can detect day and night without any extra artificial light.  Then adjust PHOTO_CELL_BRIGHTNESS in the code to always be off during the day and  always on at night.  That will be easiest.  A real-time-clock and timers that account for sunrise and sunset throughout the year is over complicating it.

Did you test the photocell option yet in the unstable branch?  I'd like to close this ticket.

**Comment by dmonty2** [comment]
Closing ticket.
