### ISSUE TITLE
Staircase More LED's then 140

### ISSUE THREAD

**Issue by Cellman86** [dmonty2/ArduinoMotionStairLights#7]
Hello dmonty2, please can you help me?
When I take over 140 LED's then the PIR Sensors do not turn the LED's on anymore. The more LEDs are to be controlled, the longer it takes until the motion detectorr react (with 120 LED's the Motion detector needs after the rainbow sequence about 1 minute to react). I hope you have a solution for me? Thanks a lot. Sorry for my bad english but I am a German ^^

Friendly Greats

**Comment by dmonty2** [comment]
I do not have that 144 leds to test with.  So here are 3 different things to look into:
* Refresh interval is too fast while waiting for PIR motion.  Could find and replace:
```cpp
stage = off;
```
with:
```cpp
stage = off;
effectInterval = 150;
```

* Move the motion detectors to the interrupt pins and add an interrupt on PIN_PIR_UP, PIN_PIR_DOWN.  This interrupt would replace the readSensors() function inside the loop().
https://playground.arduino.cc/Code/Interrupts
https://www.arduino.cc/reference/en/language/functions/external-interrupts/attachinterrupt/

* Micro controller could be running out of RAM.

**Comment by Cellman86** [comment]
Thanks for your ideas. I will try it and give feedback in a few days. Friendly Greets :-)

**Comment by dmonty2** [comment]
No feedback from proposed solution, closing issue.
