### ISSUE TITLE
Hey there

### ISSUE THREAD

**Issue by pepsiaddict82** [dmonty2/ArduinoMotionStairLights#8]
I am just wondering where in your code one could change how fast the stairs llight up? Hope you still read these messages here!

 Thanks so much for the awesome project as well, I had really hoped to not have to dive into the coding from scratch, and yours was by far the best out of all the different ones I tried!

**Comment by dmonty2** [comment]
Different effects require different speeds using effectInterval.

There are different random effects so stairs light up in the "stage_grow" section of each effect function.  The speed is set in the "stage_init" for each effect.  Look at lines:
225: effectInterval = 5;
394: effectInterval = 27;
463: effectInterval = 5;

**Comment by Himansu737** [comment]
can u send me image ple

**Comment by dmonty2** [comment]
What do you want an image of?

**Comment by dmonty2** [comment]
Duplicate question.  I'm not sending gui photos of the code.  Use the code line counter to find what to adjust.    Answered again https://github.com/dmonty2/ArduinoMotionStairLights/issues/9
